### ISSUE TITLE
Not an issue but an improvement of your program

### ISSUE THREAD

**Issue by Bingo600** [Kris-Sekula/EPROM-EMU-NG#10]
Hi MyGeeky

I rewrote your EPROM_EMU_NG_FW_2.0rc3.ino
So that it uses eprom structs instead.
[EPROM_EMU_NG_FW_2.0rc3.ino.zip](https://github.com/Kris-Sekula/EPROM-EMU-NG/files/7254728/EPROM_EMU_NG_FW_2.0rc3.ino.zip)

I wonder if you would be willing to sell a bare PCB ?

**Comment by Bingo600** [comment]
It should be much easier to add a new EPROM now 
Just add it to the EEPROM struct definitions , along with the A11.A15 states , Eprom size ,  the rxFrame , and Eprom name

No more need to fiddle further down

**Comment by Bingo600** [comment]
Ohh btw 
Havent tried on real HW ... Need a PCB 

/Bingo

**Comment by Kris-Sekula** [comment]
Thanks for sharing your changes. I'll try to include those next time I release a version of the official code.

Feel free to PM me directly regarding the bare PCB (you can contact me via mygeekyhobby.com).
