### ISSUE TITLE
Incorrect handling for EPROM type 28C64 in rc9 / rc10

### ISSUE THREAD

**Issue by hubertushirsch** [Kris-Sekula/EPROM-EMU-NG#11]
There is a fatal bug in firmware 2.0rc9 and rc10 (Files EPROM_EMU_NG_FW_2.0rc9.ino and EPROM_EMU_NG_FWrc10.ino).

The (E)Eprom type with the highest ID is the 28C64 (mem_cfg=8).

If you set this type permanently (:iniE64), the next time you start the emulator in setup () the deafult type 27512 (mem_cfg=6) is set again because the following program section is faulty:
<b>
  //
  // get "last used EPROM" config from SPI_EEPROM
  //
  if ((EEPROM.read(mem_cfg) > 7) || (EEPROM.read(mem_cfg) < 1)) {
    EEPROM.write(mem_cfg,6);  // set default to 27512
    Serial.println(F("Setting default EPROM Memory to 27512"));
  }
  else {
    lastEPROM = EEPROM.read(mem_cfg) ;
    Serial.println(String("Config: Last EPROM used is ") + memTable[lastEPROM]);
  } 
</b>
The <code>if statement</code> must be like this:
<b>
  if ((EEPROM.read(mem_cfg) > 8) || (EEPROM.read(mem_cfg) < 1)) {
</b>
If this error is corrected, access to memTable[] will fail because there is no index 8 there:
<b>
const char* memTable[8] = {"27xx","2716","2732","2764","27128","27256","27512","28256"}; // lookup table for memory type
</b>
The table must contain an element for index 8:
<b>
const char* memTable[8] = {"27xx","2716","2732","2764","27128","27256","27512","28256","28C64)}; // lookup table for memory type
</b>
Greetings
Ralf aka Hubert

**Comment by Kris-Sekula** [comment]
Confirmed, this is definitely "self inflicted" bug :) Thank you for finding it and sharing the details, as always you are a pro Ralf! I'll get the code updated tonight.

**Comment by hubertushirsch** [comment]
For more clarity I have named the EPROM IDs symbolically and use the names instead of numbers in all places.
<b>
enum {noROM, rom2kB, rom4kB, rom8kB, rom16kB, rom32kB, rom64kB, romE32kB, romE8kB, lastType};
</b>
Same order as the names in memTable[]. This will make the code
<b>
//
// get "last used EPROM" config from SPI_EEPROM
//
if ((EEPROM.read(mem_cfg) >= lastType) || (EEPROM.read(mem_cfg) < rom2kB)) {
EEPROM.write(mem_cfg, rom64kB); // set default to 27512
Serial.println(F("Setting default EPROM Memory to 27512"));
}
else {
lastEPROM = EEPROM.read(mem_cfg) ;
Serial.println(String("Config: Last EPROM used is ") + memTable[lastEPROM]);
}
</b>
or elsewhere
<b>
  switch (eprom) {
    case rom2kB:
      digitalWrite( EN_A11, LOW );
      digitalWrite( EN_A12, LOW );
      digitalWrite( EN_A13, LOW );
      digitalWrite( EN_A14, LOW );
      digitalWrite( EN_A15, LOW );
      break;
    case rom4kB:
      digitalWrite( EN_A11, HIGH );
      digitalWrite( EN_A12, LOW );
      digitalWrite( EN_A13, LOW );
      digitalWrite( EN_A14, LOW );
      digitalWrite( EN_A15, LOW );
      break;
    case rom8kB:
    case romE8kB:
      digitalWrite( EN_A11, HIGH );
      digitalWrite( EN_A12, HIGH );
      digitalWrite( EN_A13, LOW );
      digitalWrite( EN_A14, LOW );
      digitalWrite( EN_A15, LOW );
      break;
    case rom16kB:
      digitalWrite( EN_A11, HIGH );
      digitalWrite( EN_A12, HIGH );
      digitalWrite( EN_A13, HIGH );
      digitalWrite( EN_A14, LOW );
      digitalWrite( EN_A15, LOW );
      break;
    case rom32kB:
.......
</b>
Ralf

**Comment by Kris-Sekula** [comment]
Thanks Ralf, if you don't mind please attach your version of the file here
and I'll update the repository.

Kris

**Comment by hubertushirsch** [comment]
Hi Kris,

I have corrected the code of the original rc9 file. The temporary name is v20rc9-fix1.
You have to adapt the file name and the internal version string to your naming scheme.
The complete file and a diff file are included.

[v20rc9-fix1.ino.txt](https://github.com/Kris-Sekula/EPROM-EMU-NG/files/7534162/v20rc9-fix1.ino.txt)
[v20rc9-fix1.diff.txt](https://github.com/Kris-Sekula/EPROM-EMU-NG/files/7534160/v20rc9-fix1.diff.txt)

Regards
Ralf

**Comment by Kris-Sekula** [comment]
Thank you Ralf, I used your version of the file (after adding what was in rc10) and published it as rc11. Thanks again for taking the time to report and for sharing your code!
