### ISSUE TITLE
Possible to support 24C64WP SOP 8 64-Kbit serial I2C bus EEPROM?

### ISSUE THREAD

**Issue by ArcadeHustle** [Kris-Sekula/EPROM-EMU-NG#13]
[m24c64wp.pdf](https://github.com/Kris-Sekula/EPROM-EMU-NG/files/7612754/m24c64wp.pdf)

**Comment by Kris-Sekula** [comment]
hmm... you need to be more specific, 24C64WP as a Target memory or as a
replacement of the 25LC512 SPI EEPROM?

Kris

**Comment by ArcadeHustle** [comment]
As a target memory for mem_type: https://github.com/Kris-Sekula/EPROM-EMU-NG/blob/master/Software/EPROM_NG_v2.0rc3.py#L290

**Comment by Kris-Sekula** [comment]
nope unfortunately the emulator works with a "parallel" memory bus, the
24C64WP is I2c, different hardware configuration would be required... but
would not be too complex to implement, what is the use-case?

**Comment by ArcadeHustle** [comment]
A large number of devices make use of small i2c flash memories, including video game saves, and toys like Tomogatchi Digimon use them for character settings, or game firmware. 

This will enable reverse engineering of an entire class of devices that is not supported now. For example sprite swapping with Digimon could be very easy with your tool supporting this style of chip. 
https://twitter.com/rayjt9/status/1371553018496352266
https://twitter.com/BRV64/status/1352826675344461824

Thanks for your input.

**Comment by ArcadeHustle** [comment]
BIOS's may often store settings in an EEPROM of this type as well. Sega RingEdge arcade system is one such system that stores Intel Management Engine on an i2c flash chip for example. Laptop passwords for administrative features can also live in these sort of EEPROMs. 
https://hackaday.com/2021/03/24/removing-supervisor-passwords-and-learning-python/

cheers!

**Comment by Kris-Sekula** [comment]
The EEPROM I2C bus is a "shared" bus, so in most cases, you can plug a simple I2C programmer (or an Arduino with a bit of code) and re-program the EEPROM. It really makes more sense to do it with a different device.

**Comment by ArcadeHustle** [comment]
"and re-program the EEPROM" reprogramming isn't the issue. Real time watching of the changes would be nice. Thanks for your consideration. Will have to search elsewhere for the solution.
