### ISSUE TITLE
Trace feature

### ISSUE THREAD

**Issue by AMT-Cheif** [Kris-Sekula/EPROM-EMU-NG#16]
do you think is it possible to implement trace feature in your fw without lose to much performance?
with trace I mean see in real time which address/data is access from the circuit where the emulator is mounted.

**Comment by Kris-Sekula** [comment]
Unfortunately, it's not possible with the current hardware design.

**Comment by AMT-Cheif** [comment]
do you have any suggestion to start a new desgn?
