### ISSUE TITLE
Next time, support 32 pin devices...

### ISSUE THREAD

**Issue by mdhampton** [Kris-Sekula/EPROM-EMU-NG#18]
It would make things easier for larger roms (like bios for old PC's made from new(ish) parts (EMM 8088, etc). And you could replace the two RAM chips with a single 512kx8 ram. If I ever have time, I may fork this and attempt it, but I have lots on my plate already...

**Comment by Kris-Sekula** [comment]
Good suggestion, there are other ways this project could be improved, but by the time those adjustments are done it may make it way too complicated and  a completely new approach is probably needed - cpld/rp2040 etc.
