### ISSUE TITLE
assembled devices

### ISSUE THREAD

**Issue by interbiznw** [Kris-Sekula/EPROM-EMU-NG#23]
I didn't see any assembled devices or bare boards anywhere so I had some boards made, and bought parts to assemble them

I have some if  anyone needs.. I can get you bare board, or fully assembled/programmed ready to go units>>https://store.interbiznw.com/

**Comment by Kris-Sekula** [comment]
I also offer them via eBay, https://www.ebay.com/itm/174408084902

**Comment by Kris-Sekula** [comment]
due to my travel, my ebay store listing are not showing as I have "away"
enabled. The listings will show up starting tomorrow.

**Comment by Kris-Sekula** [comment]
I bought last batch from DigiKey, I see they are out of stock currently but
I'm those will be re-stocked at some point - it's a standard item that they
normally offer. Their website says TC74HC541APF-ND will be back in stock in
November

**Comment by Kris-Sekula** [comment]
I now recommend populating RN3, without it the inputs of address lines are
floating and this can sometimes cause issues with U6 going into "CMOS
latchup" (heats up and fails)
