### ISSUE TITLE
HW Version 2.2d - June 2022 issues with TLY-3100-28P and silk screen

### ISSUE THREAD

**Issue by pocoaust** [Kris-Sekula/EPROM-EMU-NG#24]
G'day,
I made this version, and ordered 10x  28 pin TLY-3100 -28P.  I assemble the unit, but cannot get the Probe to work.  I installed the 40 Pin header in position 1 and 2 as per silk screen, but the signals are all over the place.  When I probed them, they are not in the correct order for the TLY plug.  Also, the IC numbers are different on the top and bottom of the silk screen, so which is actually correct.
Thanks
Paul

**Comment by Kris-Sekula** [comment]
Hey Paul,

Sorry to hear you're having issues with the probes. These days I'm only
using the TLY-3100-28P, so this is a confirmed working solution. As long as
you solder the connector to position 1,2 you should be fine. It's likely
somewhere with the cable assembly you're having issues.
Have you seen my assembly video?
https://youtu.be/pb_EF_JVYxc?si=U0fAcKkOXZdQ7scs&t=810
There are also some details here:
https://github.com/Kris-Sekula/EPROM-EMU-NG/blob/master/Probe_Design.pdf

Both links show the other type of probe, but in general the instructions
are identical ... one difference will the the reset hooks, when using
position 1-2, the "active low" reset will come out on the first wire of the
ribbon cable (usually the only red wire) and the "active high" will be 2nd
wire.

Btw, If you send a picture of your assembled cable I may be able to tell
you if it's correct.

Kris

P.S> Agree, the IC markings on the PCB are incorrect for the output
buffers, the markings on top layer are fine, the ones on bottom layer are
incorrect.

**Comment by pocoaust** [comment]
Hi mate,

Thanks for the quick response.  It was my mistake.  My probes were fine, 
but it turns out 2 of the 10 541 IC's I brought are faulty from new.  I 
made another cable and it was the same as the old ones, so I checked all 
the IC's and found one Bad 541, went to replace it but decided to test 
before, and also found the replacement was faulty....

I think I may have reversed the cable (i just had pin headers with no 
key) when i couldn't get unit to work, and thats why when i traced the 
signals it appeared wrong. (Sorry, my mistake)

Thanks again for your help, and great work on this project.

Paul



------ Original Message ------
From "Kris Sekula" ***@***.***>
To "Kris-Sekula/EPROM-EMU-NG" ***@***.***>
Cc "pocoaust" ***@***.***>; "Author" ***@***.***>
Date 14/11/2023 7:02:30 PM
Subject Re: [Kris-Sekula/EPROM-EMU-NG] HW Version 2.2d - June 2022 
issues with TLY-3100-28P and silk screen (Issue #24)

>
>Hey Paul,
>
>Sorry to hear you're having issues with the probes. These days I'm only
>using the TLY-3100-28P, so this is a confirmed working solution. As 
>long as
>you solder the connector to position 1,2 you should be fine. It's 
>likely
>somewhere with the cable assembly you're having issues.
>Have you seen my assembly video?
>https://youtu.be/pb_EF_JVYxc?si=U0fAcKkOXZdQ7scs&t=810
>There are also some details here:
>https://github.com/Kris-Sekula/EPROM-EMU-NG/blob/master/Probe_Design.pdf
>
>Both links show the other type of probe, but in general the 
>instructions
>are identical ... one difference will the the reset hooks, when using
>position 1-2, the "active low" reset will come out on the first wire of 
>the
>ribbon cable (usually the only red wire) and the "active high" will be 
>2nd
>wire.
>
>Btw, If you send a picture of your assembled cable I may be able to 
>tell
>you if it's correct.
>
>Kris
>
>P.S> Agree, the IC markings on the PCB are incorrect for the output
>buffers, the markings on top layer are fine, the ones on bottom layer 
>are
>incorrect.
>
>
>
>

**Comment by pocoaust** [comment]
Okay story thickens....
I got working with 28pin no issue, but when i tried to use the 24 pin 
adaptor, no go.

i have placed the 40 pin IDC in position 1/2 as per instructions on 
board.  When i buzzed the VCC line, with this setup, the VCC is now on 
Pin 8, no pin 7 as in the Probe Diagram.  I then wired pin 8 to pin 24 
VCC after removing the A13 line which is shown still connected on the 
Probe Diagram. This now goes to the fuse directly.

I then wired pin 11, now A7 to Pin one on the Socket.

It now works.

So, is this because the IDE connector needs to be in 2/3?  Underneath? 
or am I just going mad.

I suspect that the issue is the diagram was done for a previous version 
and this version reverses the sides the pins are on when you install the 
IDC in 2/3 position maybe?

Also, this may mean the reset signal are reversed as well......

This is why I was getting the odd readings for signals originally... ;-)

Any ideas?
Paul



------ Original Message ------
From "Paul O'Connor" ***@***.***>
To "Kris-Sekula/EPROM-EMU-NG" 
***@***.***>
Date 15/11/2023 6:51:23 AM
Subject Re[2]: [Kris-Sekula/EPROM-EMU-NG] HW Version 2.2d - June 2022 
issues with TLY-3100-28P and silk screen (Issue #24)

>Hi mate,
>
>Thanks for the quick response.  It was my mistake.  My probes were 
>fine, but it turns out 2 of the 10 541 IC's I brought are faulty from 
>new.  I made another cable and it was the same as the old ones, so I 
>checked all the IC's and found one Bad 541, went to replace it but 
>decided to test before, and also found the replacement was faulty....
>
>I think I may have reversed the cable (i just had pin headers with no 
>key) when i couldn't get unit to work, and thats why when i traced the 
>signals it appeared wrong. (Sorry, my mistake)
>
>Thanks again for your help, and great work on this project.
>
>Paul
>
>
>
>------ Original Message ------
>From "Kris Sekula" ***@***.***>
>To "Kris-Sekula/EPROM-EMU-NG" ***@***.***>
>Cc "pocoaust" ***@***.***>; "Author" 
>***@***.***>
>Date 14/11/2023 7:02:30 PM
>Subject Re: [Kris-Sekula/EPROM-EMU-NG] HW Version 2.2d - June 2022 
>issues with TLY-3100-28P and silk screen (Issue #24)
>
>>
>>Hey Paul,
>>
>>Sorry to hear you're having issues with the probes. These days I'm 
>>only
>>using the TLY-3100-28P, so this is a confirmed working solution. As 
>>long as
>>you solder the connector to position 1,2 you should be fine. It's 
>>likely
>>somewhere with the cable assembly you're having issues.
>>Have you seen my assembly video?
>>https://youtu.be/pb_EF_JVYxc?si=U0fAcKkOXZdQ7scs&t=810
>>There are also some details here:
>>https://github.com/Kris-Sekula/EPROM-EMU-NG/blob/master/Probe_Design.pdf
>>
>>Both links show the other type of probe, but in general the 
>>instructions
>>are identical ... one difference will the the reset hooks, when using
>>position 1-2, the "active low" reset will come out on the first wire 
>>of the
>>ribbon cable (usually the only red wire) and the "active high" will be 
>>2nd
>>wire.
>>
>>Btw, If you send a picture of your assembled cable I may be able to 
>>tell
>>you if it's correct.
>>
>>Kris
>>
>>P.S> Agree, the IC markings on the PCB are incorrect for the output
>>buffers, the markings on top layer are fine, the ones on bottom layer 
>>are
>>incorrect.
>>
>>
>>
>>

**Comment by Kris-Sekula** [comment]
Paul,
Sorry some of the instructions are out of date... when the probe cable
diagram was created, I was only using the ADAMTech FDP-628 "DIP Probe" (or
FDP-624 for 24 pin)... later I found the TLY-3100-28P but this one has all
connections "mirrored" .. and there is no 24 pin equivalent. The solution
was to add the second row of pins and give users the choice to solder 1-2
for the TLY probe or 2-3 for the FDP probe.

You mentioned you managed to successfully get the 28 pin probe working with
TLY-3100-28P ... but when building the 24 pin cable what type of DIP probe
are you using? You can't mix TLY and FDP on the same PCB ...

When emulating 24 pin devices (2716/2732) you can use the same 28 pin
cable, but plug it to your target the way that the top 4 pins are hanging
outside the 24pin dip socket ... and it will work.

Kris

**Comment by pocoaust** [comment]
Hi mate, thats the answer....

I use the TLY-3100-28P and I cut off the last 4 pins and plastic weld 
the end....  Thats why it didn't work.  I ended up with off set 24 Pin.

So can I suggest you add the  FDP 24 pin part number to the probe pdf 
and a caution not to note to say you must use the same with the FDP on 
the 28 pin Probe if you wish to use both.

The work around is as I described to get it working ;-)

Thanks again for your help.

Paul


------ Original Message ------
From "Kris Sekula" ***@***.***>
To "Kris-Sekula/EPROM-EMU-NG" ***@***.***>
Cc "pocoaust" ***@***.***>; "Author" ***@***.***>
Date 15/11/2023 9:26:44 AM
Subject Re: [Kris-Sekula/EPROM-EMU-NG] HW Version 2.2d - June 2022 
issues with TLY-3100-28P and silk screen (Issue #24)

>
>Paul,
>Sorry some of the instructions are out of date... when the probe cable
>diagram was created, I was only using the ADAMTech FDP-628 "DIP Probe" 
>(or
>FDP-624 for 24 pin)... later I found the TLY-3100-28P but this one has 
>all
>connections "mirrored" .. and there is no 24 pin equivalent. The 
>solution
>was to add the second row of pins and give users the choice to solder 
>1-2
>for the TLY probe or 2-3 for the FDP probe.
>
>You mentioned you managed to successfully get the 28 pin probe working 
>with
>TLY-3100-28P ... but when building the 24 pin cable what type of DIP 
>probe
>are you using? You can't mix TLY and FDP on the same PCB ...
>
>When emulating 24 pin devices (2716/2732) you can use the same 28 pin
>cable, but plug it to your target the way that the top 4 pins are 
>hanging
>outside the 24pin dip socket ... and it will work.
>
>Kris
>
>

**Comment by Kris-Sekula** [comment]
I updated the pdf. Thanks for your patience and for reporting the documentation issues.

**Comment by pocoaust** [comment]
Thanks for you work.  I,can't get the unit to work in the real world, but I
am using a bat84 instead of the bat 48 which I will get tomorrow.
Hopefully that fixes the remaining issue.

Thanks again for your help.

Take care.

**Comment by pocoaust** [comment]
Finally bit the bullet and ordered the correct sockets 28 and 24 pin.  Will
make another board with plug on alternates position.

Take care
Paul
