### ISSUE TITLE
2716

### ISSUE THREAD

**Issue by smdjeff** [Kris-Sekula/EPROM-EMU-NG#25]
24 pin devices like the 2716 and 2732 are supported by keeping the top 4 pins of the 28pin emulator probe unplugged. The power must be provided by the USB cable.

**Comment by Kris-Sekula** [comment]
Another option is to use this adapter - it was specifically designed to work with the emulator. https://www.pcbway.com/project/shareproject/2364_to_2764_or_2716_2732_to_2764_27512_adapter.html
