### ISSUE TITLE
Cannot get FDP type probes to work with V2.2d board

### ISSUE THREAD

**Issue by pocoaust** [Kris-Sekula/EPROM-EMU-NG#26]
Kris,

I got the new FDP-624-T 24 pin and 28 pin from DIGIkey.   I remade a new board and put the header into row 2/3 of Ver 2.2d board.  If I run it on pc I can program and then read the emulator in TL866Pro, but as soon as I put either the 28Pin into a Amstrad CPC (27256), or the 24 pin into a TEC one-a (2716), the U6 starts to heat up and it does not work.

The 28 Pin worked in the previous board i made with the same Amstrad but with with the TLY probe and Header connector in Position 1/2

When i buzz the pins from the FDP out, they appear correct according to the Schematic.  I have tried with the RN2 installed and removed, same issue.

Any ideas?

**Comment by pocoaust** [comment]
MY main need is to support 2716 in emulation.

**Comment by Kris-Sekula** [comment]
Just to confirm a few facts:

1. You currently have two emulators, one assembled to use the TLY probe and
one assembled to use the FDP(both 24 and 28) pin probes?
2. The TLY 28 pin based emulator works fine with your Amstrad CPC (as
27256)?
3. The new unit assembled to support the FDP probe, you are currently
experiencing issues with U6 heating up.

I've seen U6 getting hot if RN2 is left unpopulated, so make sure RN2 and
RN3 are in at all times - those lead to address bus inputs and you just
don't want to leave inputs floating.

If you've not noticed the U6 getting hot before installing RN2, it's
possible that U6 is now broken - I would suggest swapping it - or as a
minimum test it with your TL866 to confirm that it "survived" the heat of
CMOS latchup.

Are you able to "read" the 24pin probe via the TL866?

Try the following order of power sequence:

When powering up the emulator:
1. With both the emulator and your target system (the one you plug your
emulator into) powered off, install the emulator probe.
2. Power up your target
3. plug the usb cable from the computer to the emulator.
4. upload binary to the emulator - should be ready to use.

When powering off the emulator:
1. Remove the USB cable from the emulator.
2. Power off the target system
3. You can remove the emulator probe from your target at this point.

If you're still experiencing U6 lockup, swap it for the 74LS595 or 74F595
versions - those are TTL and will not lockup.

Kris

**Comment by pocoaust** [comment]
Hi mate,  Merry Xmas and Happy new Year.

Yes, I have 2 versions....  (Gave TLY probe one to mate who only needed 
27256 emulation.)  Only has RN2 installed on this one as per Assembly 
instructions  April 2021 Ver 2.2A  This worked on Amstrad CPC.

Built new one yesterday with FDP probes....

added RN3....  Assembly instructions shows as empty  April 2021 Ver 2.2A

Found a bad gate on one 541... 4 in this batch...  ALi express ....  
AHHHHHH

Now 28 Pin FDP 28 pin now works in Amstrad and TLL866

24 Pin in Tec-1a (2716 emulation) still does not work, but reads in 
TL866 okay....

I have tried cutting VPP line Pin 21 on 24 pin FDP Probe, as is still 
connected to A11, but still no go.

I have tried removing RN2, but behaves worse.

Should I bend up the 2 pins on RN2 for the CS and OE lines? Could it be 
like the spectrum?

The 595 now only still heats after after attempting to use and cycling 
power several times on Tec 1a.....  It then continues to grow hot even 
when TEC-1a is Powered down?  to stop I must power down emulator 
.....Cmos hangup?

Any help appreciated.

Paul







------ Original Message ------
From "Kris Sekula" ***@***.***>
To "Kris-Sekula/EPROM-EMU-NG" ***@***.***>
Cc "pocoaust" ***@***.***>; "Author" ***@***.***>
Date 31/12/2023 3:26:40 PM
Subject Re: [Kris-Sekula/EPROM-EMU-NG] Cannot get FDP type probes to 
work with V2.2d board (Issue #26)

>
>Just to confirm a few facts:
>
>1. You currently have two emulators, one assembled to use the TLY probe 
>and
>one assembled to use the FDP(both 24 and 28) pin probes?
>2. The TLY 28 pin based emulator works fine with your Amstrad CPC (as
>27256)?
>3. The new unit assembled to support the FDP probe, you are currently
>experiencing issues with U6 heating up.
>
>I've seen U6 getting hot if RN2 is left unpopulated, so make sure RN2 
>and
>RN3 are in at all times - those lead to address bus inputs and you just
>don't want to leave inputs floating.
>
>If you've not noticed the U6 getting hot before installing RN2, it's
>possible that U6 is now broken - I would suggest swapping it - or as a
>minimum test it with your TL866 to confirm that it "survived" the heat 
>of
>CMOS latchup.
>
>Are you able to "read" the 24pin probe via the TL866?
>
>Try the following order of power sequence:
>
>When powering up the emulator:
>1. With both the emulator and your target system (the one you plug your
>emulator into) powered off, install the emulator probe.
>2. Power up your target
>3. plug the usb cable from the computer to the emulator.
>4. upload binary to the emulator - should be ready to use.
>
>When powering off the emulator:
>1. Remove the USB cable from the emulator.
>2. Power off the target system
>3. You can remove the emulator probe from your target at this point.
>
>If you're still experiencing U6 lockup, swap it for the 74LS595 or 
>74F595
>versions - those are TTL and will not lockup.
>
>Kris
>
>

**Comment by Kris-Sekula** [comment]
Hey Paul, thanks, and Happy New Year to you too. 

The recommendation on RN3 changed since the document was published - I updated and put a note into the assembly document today. Not populating RN3 will sometimes cause the U6 to go into CMOS lockup - the only way to "un-lock" it, is to remove power from the emulator (both power from target and power from USB) ... the lockup can happen based on all sorts of conditions and is very "case" specific... power cycling the target while it's connected to a computer can cause the issue, so I'm not surprised this is what you see when you cycle multiple times power on your TEC.

I am not sure why your TEC 1a is not playing well with the emulator ... probably worth isolating the pull-up on OE and CE lines to see if it makes any difference, considering that your TL866 "reads" the emulator correctly it must be somehow the interaction between the units...

I know TEC-1F works fine, as I have that documented in the "use-cases" sent to me by William. I'll take a look at the schematic on 1a and try to give you some advice. 

Do you have a scope, so that we can take a look at those signals while the emulator is plugged in?

Kris
