### ISSUE TITLE
Errors in EpromEmu_2_2d_BoM_DigiKey_v1.xlsx

### ISSUE THREAD

**Issue by ellensp** [Kris-Sekula/EPROM-EMU-NG#27]
EpromEmu_2_2d_BoM_DigiKey_v1.xlsx list the following

```
Index	Quantity	Part Number	    Manufacturer Part Number	Description	                Customer Reference
5	2	        4610X-1-103LF-ND    4610X-101-103LF             RES ARRAY 9 RES 10K OHM 10SIP	RN2
31	1	        A786AR-ND           10-0518-10	                CONN SOCKET SIP 10POS GOLD	RN2

```

but the assembly documents says you need RN2 and RN3

So these are in error.

Index 5 the customer reference should be RN2, RN3 
Index 31 the quantity should be 2 and the customer reference should be RN2, RN3

**Comment by Kris-Sekula** [comment]
you're correct, thanks for spotting and reporting ...I've updated the Bom. Also just FYI, I've updated the RNs to 47k from 10k ... either value is ok, but I'm now using 47k in the assembled emulators that I offer.
