### ISSUE TITLE
Testing Firmware EPROM_EMU_NG_FW_2.0rc3.ino

### ISSUE THREAD

**Issue by hubertushirsch** [Kris-Sekula/EPROM-EMU-NG#4]
Thank you for providing the firmware **EPROM_EMU_NG_FW_2.0rc3.ino** for testing.
The firmware works flawlessly in my environment.

I would prefer to switch off the red LED during the long press together with EN_RST=HIGH.
I.e. when the reset signal is activated, the LED goes out and when the button is released it lights up again.

I tried out a few small code changes.
Here is the summary.

//  - remove unused variable 'page_ctn'
//  - move variable 'spi_address' from global scope to function **load_SPIEEPROM()**
//      The variable is only used in this function.
//      The positive side effect: Saves 20ms more in loading SRAM
//  - simplify filling shift registers in **writeMemoryLocation()**, two variables are omitted.
//      No effect on speed.
//  - in long press button move the turn LED off few lines up, so the 150ms is included in LED off time
//      This makes it easier to recognize the triggering of the reset and release the button at the right time

In addition, some comment lines are incorrect in the rxframe evaluation:
:iniAuto0
:iniSPI0

The diff file is attached.

In the Python script **EPROM_NG_v2.0rc3.py**, reference is still made to the old function (turm autoLoad off) for Long Press Button. That can be omitted.

Greetings
Ralf

[v20rc3update1.diff.txt](https://github.com/Kris-Sekula/EPROM-EMU-NG/files/5742359/v20rc3update1.diff.txt)

**Comment by Kris-Sekula** [comment]
Thanks for the feedback Ralf.

The LED going OFF during long press was already implemented in rc3 (line
584 and 588) to indicate the "long-press reset" was successful.

I'll integrate the other comments into rc4 when it's out.

Thanks again!

Kris

**Comment by hubertushirsch** [comment]
Hi Kris,

> The LED going OFF during long press was already implemented in rc3

yes, but I think is better in handling for the operator that the LED already goes out when the reset is initiated.
That was my feeling when trying it out.
So I moved the statement **digitalWrite( LED_G, LOW )** up a few lines.
```
    } else {                             // Button not released after 500ms
      delay(1000);                       // Wait 1s more
      if (digitalRead(LD_BTN) == LOW) {  // Button not released after (500+1000)ms = long press
        // long press resets target
        digitalWrite( LED_G, LOW );      // turn the LED off to indicate the RESET was initiated <== LED turned off 
        digitalWrite( EN_RST, HIGH);
        delay(150);
        digitalWrite( EN_RST, LOW );
        Serial.println(F("-> Resetting target via button"));
//        digitalWrite( LED_G, LOW );      // turn the LED off to indicate the RESET was succesful ==> shift this some lines up
        while (digitalRead(LD_BTN) == LOW) {
          delay(100);                    // wait for releasing button
        }
        digitalWrite( LED_G, HIGH );    //
      }
    }

```
 
Ralf

**Comment by Kris-Sekula** [comment]
Ah, ok I see now. No problem, this doesn't make much difference to me, so
I'm happy to follow your recommendation. I'll add this change to rc4 as well

Thanks again :)
Kris
