### ISSUE TITLE
23xx support

### ISSUE THREAD

**Issue by eh** [Kris-Sekula/EPROM-EMU-NG#7]
I was wondering if you would consider adding 23xx support, the difference is only in pinout. This would make it handy to use in things like ZX81/TS1000 without an adapter.

**Comment by Kris-Sekula** [comment]
Hi Erik. I have used the emulator with Commodore 64 to emulate the 2364 PROM. You simply can select 2764 memory. On the hardware side, you still need an adapter as 2364 only is a 24 pin device and the emulator is 28pin, there is also a pinout difference, but more importantly, 2364 only has one control signal /CS, but most EPROMs and the emulator requires both /CE and /OE to work. You can buy one of the popular adapters for a Commodore or you can order a PCB from PCB way that I created to cover both the 23xx and the 2716/2732 use-cases with my emulator. See here [https://www.pcbway.com/project/shareproject/2364_to_2764_or_2716_2732_to_2764_27512_adapter.html](url)

**Comment by eh** [comment]
I have a dead Timex Sinclair 1000 and I suspect the ROM (I can verify ULA/Z80 functionality) and I have purchased an adapter already, just not gotten around to using it. The thing is, ZX81/TS1000 (and more?) have a DIP28 ROM footprint. Mine is even socketed. As it happens I had just recently purchased your emulator, so I thought I could try that.

To be honest any explanation for why it can't do 23xx is probably lost on me for now, as I'm just getting into this stuff (I picked up your mgh80 kit at the same time). The adapter boards I've seen (including the one I have) just move pins around, and maybe provide A14/A15 for bank selection. There's no magic to provide CE/OE. So I figured just re-assigning some pin locations, similar to what an adapter does but in software, would work. I had a look at your arduino source but don't have the time just now to figure out where EEPROM.h is getting its pin definitions.

I'm probably in over my head and will take your word for it that it can't be done. For what it's worth I've had no issues with either of your kits. They were a joy to assemble and the emulator has come in handy for other projects since I built it. Not waiting on my cheap UV eraser (and then waiting again because it almost never fully erases) has made it very much worth owning.

**Comment by Kris-Sekula** [comment]
Erik, I don't have a Timex / ZX81 to try, but I had a look at the board and schematic: [http://www.mainbyte.com/ts1000/drw_board.jpg](url) and it looks like the ROM is a 2364 - and those are 24 pins. Maybe you have a different revision of the PCB with a 28pin footprint.  The "software" trick for re-arranging the Address / Data lines is possible (I use it to support 28C256) but the control signals on the emulator are directly connected to the output buffer (74hc541). For the buffer to open you need both /CE and /OE to be logic low... the ZX81 can supply only one of those control signals the other has to be routed to the ground - most of the adapters for Commodore including my adapter works the same way by re-routing one of the control signals to ground. 

I have a ZX Spectrum and for that one, you need to modify the motherboard a bit to support standard EPROMS (including my emulator). Additionally, the way data/address lines are arranged in the spectrum, you may have to remove the pull-up resistor network from the emulator for this to work.

**Comment by eh** [comment]
No matter, as I was implying it is a DIP24 2364 (in a DIP28 socket/footprint) and that's what I was hoping to emulate. I've attached a picture of mine, and you can search google images for other examples. It's the norm. 1,2,27,28 are wired to support DIP28 in I suppose Sinclair fashion, whatever was cheapest they could get at the time.

But I have to apologize, I've actually conflated two things here. The fact that the TS1000 has a DIP28 footprint and is wired to support a longer chip is not relevant. I spent a lot of hours on this thing today and it's what I had on my mind. Ignore the DIP28 stuff, sorry about that.

Looking over the pinout I think I have a better understanding, an adapter will tie CE low and bring OE to the CE pad. I guess if you can't make assumptions about these pins in a hypothetical "23xx" mode then it can't be done. I was thinking "arduino pins are mapped to eprom pins" which is wrong and I should have looked at your schematic. It's been a long day of fighting a video gremlin on this board, so again, sorry about all this.

Looking at my picture I've just noticed the RAM also has a DIP28 outline ... at any rate I have an adapter to build.
![PXL_20210329_025639712](https://user-images.githubusercontent.com/97576/112781774-1cfb3100-9011-11eb-8ce8-12781d0223e3.jpg)

**Comment by Kris-Sekula** [comment]
no worries Erik, looks like you got an "issue 3" PCB that has the option to use larger ICs - something I've just learned today. As you discovered, some of this control logic has to be done in hardware, so you will need a small adapter. I'll close the GitHub issue.
