### ISSUE TITLE
Emulating an AT27C256

### ISSUE THREAD

**Issue by InPermutation** [Kris-Sekula/EPROM-EMU-NG#8]
_Please consider this a draft note-to-self, since I don't have time tonight to write a pull request._

The pinout between an AT27C256 and a 28256 differs in that the EEPROM's A14 is on pin 1, with /WE on pin 27, while the 28256 EPROM has Vdd on pin 1 and A14 on pin 27.

So, since in the EPROM-EMU-NG, pin 1 is A15, and A14 will be held high ("write enable" not asserted), we can write a little Python script to convert a 32K binary file into a 64K file padded with junk in addresses `0000:3FFF` and `8000:c000`:

```python
#!/usr/bin/env python3

import sys

if __name__ == "__main__":
    with open(sys.argv[1], "rb") as infile:
        data = infile.read()
        assert len(data) == 0x8000, f"len must be {0x8000}; was {len(data)}"
    with open(sys.argv[2], "wb") as outfile:
        outfile.write(b'\xff' * 0x4000) # junk
        outfile.write(data[0:0x4000])
        outfile.write(b'\xff' * 0x4000)  # junk
        outfile.write(data[0x4000:0x8000])
```

then write it out like usual:

```
% python3 EPROM_NG_v2.0rc3.py -mem 27512 -spi y -auto y ./a512.out /dev/tty.usbserial-1410 -start 0 -map y
```

I used a TL866 II+ with [`minipro`](https://gitlab.com/DavidGriffith/minipro/) to confirm that this reads correctly as a 27C256:

```
% minipro -p AT28C256 -r a.test
```

And, I attached it in place of the EEPROM of my Ben Eater 6502, and it boots up correctly!

**Comment by InPermutation** [comment]
Data writes at about 1.6 kbps, so we can speed this up by not even writing the junk bytes. First optimization: use the `-start 4000` parameter, and remove the first `# junk` line.

Second optimization: write two separate files, write at `-start 4000` and `-start c000`. (todo: check math)

**Comment by InPermutation** [comment]
The downside to the second optimization is that RST/ goes high for a fraction of a second between the two runs, which could cause undesired operation of the target computer.

**Comment by Kris-Sekula** [comment]
Hey Jacob, great job investigating. I sent you an email, try that if you get a chance and let me know if your BE6502 boots... if it does I'll publish the files for others to try.

**Comment by Kris-Sekula** [comment]
The newly released (experimental) version of firmware and software now has EEPROM support included:
Firmware 2.0rc8 (EPROM_EMU_NG_FW_2.0rc8.ino - Arduino sketch in Firmware folder)
Software 2.0rc8 (EPROM_EMU_NG_2.0rc8.py - Python script in Software folder)

**Comment by InPermutation** [comment]
The new firmware works great, thanks @Kris-Sekula!
